databases:
  - name: urubytes_db
    plan: free
    databaseName: main_99ef
    user: knavilot

services:
  - type: web
    plan: free
    name: urubytes
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn urubytes.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urubytes_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4