# Generated by Django 5.0.3 on 2024-03-09 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgID', models.CharField(max_length=15, verbose_name='Organization ID')),
                ('name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('industry', models.CharField(max_length=80, verbose_name='Industry')),
                ('size', models.CharField(max_length=10, verbose_name='Organization Size')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('isActive', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('role', models.CharField(max_length=80, verbose_name='Role')),
                ('isAdmin', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('orgID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.CharField(choices=[('1', "I'm researching startups for investment"), ('2', "I'm looking for insights on VC firms"), ('3', "I'm a startup founder seeking insights and resources"), ('4', "I'm an industry professional following startup and VC trends")], max_length=1, verbose_name='Interest')),
                ('referrer', models.CharField(choices=[('friend', 'Through a friend'), ('industry', 'Industry publication/conference'), ('social_media', 'Social media'), ('networking', 'Webinar/Networking event')], max_length=15, verbose_name='Referrer')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
