# Generated by Django 5.0.3 on 2024-03-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dateJoined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isAdmin',
            new_name='is_staff',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isVerified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastUpdated',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
