# Generated by Django 5.0.3 on 2024-03-09 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_datejoined_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insights',
            new_name='Insight',
        ),
        migrations.RenameField(
            model_name='insight',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='insight',
            old_name='lastUpdated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='isActive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='isVerified',
            new_name='is_verified',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='lastUpdated',
            new_name='last_updated',
        ),
    ]
