# Generated by Django 5.0.3 on 2024-03-10 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='orgID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.organization'),
        ),
    ]
